-- [1] 유저 프로필 (지갑 역할)
-- 계정과 1:1 매칭되며 닉네임과 재화를 저장
create table public.profiles (
  id uuid references auth.users not null primary key,
  nickname text,
  minerals jsonb default '{"gold": 0, "rock": 0}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [2] 광물 레시피 (정적 데이터)
-- 돌의 종류, 화학식, 밀도 정보를 정의 (게임의 규칙)
create table public.mineral_recipes (
  id int generated by default as identity primary key,
  name text not null,        -- 예: Hematite
  formula text not null,     -- 예: Fe2O3
  elements jsonb not null,   -- 합성/분해 재료 (예: {"Fe": 2, "O": 3})
  base_density float not null, -- 밀도 (원자량 합계)
  base_color text default '#ffffff'
);

-- 2-1. 초기 레시피 데이터 주입
insert into public.mineral_recipes (name, formula, elements, base_density, base_color)
values 
  ('Quartz', 'SiO2', '{"Si": 1, "O": 2}', 60.1, '#e6e6fa'),
  ('Hematite', 'Fe2O3', '{"Fe": 2, "O": 3}', 159.6, '#6a0dad'),
  ('Gold Nugget', 'Au', '{"Au": 1}', 197.0, '#ffd700');

-- [3] 유저 원소 인벤토리
-- 유저가 보유한 원소(Fe, O 등)의 개수
create table public.user_materials (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  element text not null, -- 원소 기호
  amount int default 0 check (amount >= 0),
  unique(user_id, element) -- 유저당 원소별 중복 방지
);

-- [4] 돌(Stone) 데이터
-- 실제 유저가 소유한 돌. 레시피를 참조하며, DNA와 질량을 가짐
create table public.stones (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) not null,
  recipe_id int references public.mineral_recipes(id) not null, -- 종류 연결
  dna jsonb default '{}'::jsonb, -- 외형/불순물 등 절차적 데이터
  name text default 'Unnamed Stone',
  birth_date timestamp with time zone default timezone('utc'::text, now()) not null,
  current_mass float default 0.0 -- 현재 질량 (서버 정렬용)
);

-- [5] 회원가입 트리거 (자동 프로필 생성)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, nickname)
  values (new.id, '돌키우기초보');
  return new;
end;
$$ language plpgsql security definer;

-- 트리거 연결
-- (이미 존재한다면 에러가 날 수 있으니 drop 후 생성하거나, 처음 실행 시에만 사용)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

------------------------------------------------------------------------
-- [6] RLS (보안 정책) 설정
------------------------------------------------------------------------

-- 테이블 보안 활성화
alter table public.profiles enable row level security;
alter table public.mineral_recipes enable row level security;
alter table public.user_materials enable row level security;
alter table public.stones enable row level security;

-- 6-1. 프로필 정책
create policy "프로필 보기: 누구나" on public.profiles for select using (true);
create policy "프로필 수정: 본인만" on public.profiles for update using (auth.uid() = id);

-- 6-2. 레시피 정책 (읽기 전용)
create policy "레시피 보기: 누구나" on public.mineral_recipes for select using (true);

-- 6-3. 원소 인벤토리 정책 (본인만)
create policy "원소 보기: 본인만" on public.user_materials for select using (auth.uid() = user_id);
create policy "원소 수정: 본인만" on public.user_materials for all using (auth.uid() = user_id);

-- 6-4. 돌 정책 (보기는 누구나, 수정은 본인만)
create policy "돌 보기: 누구나" on public.stones for select using (true);
create policy "돌 관리: 본인만" on public.stones for all using (auth.uid() = owner_id);